### ISSUE TITLE
Adequate config values for version using titan 0.5.2

### ISSUE THREAD

**Issue by pablopareja** [bio4j/bio4j-titan#50]
Hi,

I'm having a look at the config parameters specifications [here](http://s3.thinkaurelius.com/docs/titan/0.5.2/titan-config-ref.html) and I don't see at first sight any one that could lead to drastic improvements in terms of reducing the importing process time ... https://github.com/bio4j/bio4j-titan/issues/49

any ideas?? @eparejatobes @laughedelic

**Comment by eparejatobes** [comment]
what is the status of this? I'm moving it to `0.5` anyway.
