### ISSUE TITLE
file namings

### ISSUE THREAD

**Issue by evdokim** [bio4j/bio4j-titan#62]
I got the following error:

```
[error] E:\reps\bio4j-titan\src\main\java\com\bio4j\titan\model\uniprot\TitanUniprotGraph.java:21: error: class TitanUniProtGraph is public, should be declared in a file named TitanUniProtGraph.java
[error] public final class TitanUniProtGraph
```

when I was trying to build code in the master branch of this repository. Is that already fixed somewhere should do all these renaming from "Uniprot" to "UniProt"?

**Comment by pablopareja** [comment]
`master` branch is not the reference branch right now.
It will be updated once we fix the last set of issues we had, the most up-to-date branch is: https://github.com/bio4j/bio4j-titan/tree/fix/interdependent/modules

**Comment by evdokim** [comment]
Ok supposed that, thanks
