### ISSUE TITLE
Where to get bio4j-titan-0.4.0-SNAPSHOT-fat.jar?

### ISSUE THREAD

**Issue by oxyko** [bio4j/bio4j-titan#71]
Hey,

I'm trying to install bio4j-titan locally (i.e. not in AWS) and going through the documentation I get to step 5:
bio4j-titan-0.4.0-SNAPSHOT-fat.jar (s3://snapshots.era7.com/bio4j/bio4j-titan/0.4.0-SNAPSHOT/bio4j-titan-0.4.0-SNAPSHOT-fat.jar)

Since I'm not on AWS, is there any other way I can get this jar?

Regards,
Oksana

**Comment by laughedelic** [comment]
Hi @oxyko!

This link can be translated to the following:

```
https://s3-eu-west-1.amazonaws.com/releases.era7.com/bio4j/bio4j-titan/0.4.0-RC3/bio4j-titan-0.4.0-RC3-fat.jar
```

which you can access just with your browser or any console tool (e.g. `wget`)

We have a pending pull-request which improves docs a bit (#70). I'll add this link there and merge it.

**Comment by laughedelic** [comment]
Oksana, please, check out the updated [docs/ImportingTitanBio4j.md](https://github.com/bio4j/bio4j-titan/blob/master/docs/ImportingTitanBio4j.md). The fat-jar link there is what I wrote above.

**Comment by oxyko** [comment]
Thanks! Looks good!

**Comment by laughedelic** [comment]
Ok :+1:  I'm closing this then.
